# Generated by Django 5.1.3 on 2024-12-08 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa'), ('RetailSpace', 'RetailSpace'), ('Resort', 'Resort'), ('GuestHouse', 'GuestHouse'), ('PG', 'PG')], default='Villa', max_length=200)),
                ('property_status', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Lease', 'Lease')], default='Sale', max_length=200)),
                ('location', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thiruvananthapuram', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
                ('no_of_rooms', models.IntegerField()),
                ('furnished_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], default='Furnished', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
