# Generated by Django 5.1.3 on 2024-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='estateimages'),
        ),
    ]
