# Generated by Django 5.1.4 on 2024-12-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_propertydetails_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='picture',
            new_name='property_image',
        ),
    ]
